#! /bin/bash

if [ ! -d "build" ]; then
	echo "-- making build directory..."
	mkdir build
fi
echo "-- in the build directory..."
cd build/
cmake ../
echo "-- building the executables..."
make -j2
# echo "return status is = $?"
if [ "$?" -eq 0 ]; then
	echo ""
	echo "-- build is done..."
	echo "-- Navigate to build/bin to run the 'twMD' executable."
	echo ""
else
	echo ""
	echo "-- build failed due to a compile error..."
	echo ""
fi
